parameters:
  "service-dir":
    default: "sdk/ai"
emit:
  - "@azure-tools/typespec-autorest"
options:
  "@azure-tools/typespec-autorest":
    emitter-output-dir: "{project-root}/.."
    azure-resource-provider-folder: "data-plane"
    emit-lro-options: "none"
    output-file: "{azure-resource-provider-folder}/{service-name}/{version-status}/{version}/azure-ai-telemetry.json"
  "@azure-tools/typespec-python":
    package-mode: "dataplane"
    package-dir: "azure-ai-telemetry"
    package-name: "{package-dir}"
    flavor: azure
    generate-test: false
    generate-sample: false
    examples-dir: "{project-root}/examples"
  "@azure-tools/typespec-csharp":
    package-mode: "dataplane"
    package-dir: "Azure.AI.Telemetry"
    namespace: "Azure.AI.Telemetry"
    package-name: "{package-dir}"
    model-namespace: false
    flavor: azure
    generate-test: false
    generate-sample: false
    examples-dir: "{project-root}/examples"
  "@azure-tools/typespec-ts":
    package-dir: "ai-telemetry"
    generateTest: true
    generateMetadata: false
    packageDetails:
      name: "@azure/ai-telemetry"
    flavor: azure
linter:
  extends:
    - "@azure-tools/typespec-azure-rulesets/data-plane"
  disable:
    "@azure-tools/typespec-azure-core/casing-style": "Since we have many names in the form XxxxAIXxxx"
